package com.pokemon.mebius.giraffe.base.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.pokemon.mebius.giraffe.base.entities.GiraffeExceptionInfo;
import com.pokemon.mebius.giraffe.base.entities.GiraffeHttpLogInfo;

import com.pokemon.mebius.giraffe.base.greendao.GiraffeExceptionInfoDao;
import com.pokemon.mebius.giraffe.base.greendao.GiraffeHttpLogInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig giraffeExceptionInfoDaoConfig;
    private final DaoConfig giraffeHttpLogInfoDaoConfig;

    private final GiraffeExceptionInfoDao giraffeExceptionInfoDao;
    private final GiraffeHttpLogInfoDao giraffeHttpLogInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        giraffeExceptionInfoDaoConfig = daoConfigMap.get(GiraffeExceptionInfoDao.class).clone();
        giraffeExceptionInfoDaoConfig.initIdentityScope(type);

        giraffeHttpLogInfoDaoConfig = daoConfigMap.get(GiraffeHttpLogInfoDao.class).clone();
        giraffeHttpLogInfoDaoConfig.initIdentityScope(type);

        giraffeExceptionInfoDao = new GiraffeExceptionInfoDao(giraffeExceptionInfoDaoConfig, this);
        giraffeHttpLogInfoDao = new GiraffeHttpLogInfoDao(giraffeHttpLogInfoDaoConfig, this);

        registerDao(GiraffeExceptionInfo.class, giraffeExceptionInfoDao);
        registerDao(GiraffeHttpLogInfo.class, giraffeHttpLogInfoDao);
    }
    
    public void clear() {
        giraffeExceptionInfoDaoConfig.clearIdentityScope();
        giraffeHttpLogInfoDaoConfig.clearIdentityScope();
    }

    public GiraffeExceptionInfoDao getGiraffeExceptionInfoDao() {
        return giraffeExceptionInfoDao;
    }

    public GiraffeHttpLogInfoDao getGiraffeHttpLogInfoDao() {
        return giraffeHttpLogInfoDao;
    }

}
