package com.pokemon.mebius.giraffe.base.greendao;

import com.pokemon.mebius.giraffe.base.entities.GiraffeExceptionInfo;
import com.pokemon.mebius.giraffe.base.entities.GiraffeHttpLogInfo;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import java.util.Map;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig wolfExceptionInfoDaoConfig;
    private final DaoConfig wolfHttpLogInfoDaoConfig;

    private final GiraffeExceptionInfoDao wolfExceptionInfoDao;
    private final GiraffeHttpLogInfoDao wolfHttpLogInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        wolfExceptionInfoDaoConfig = daoConfigMap.get(GiraffeExceptionInfoDao.class).clone();
        wolfExceptionInfoDaoConfig.initIdentityScope(type);

        wolfHttpLogInfoDaoConfig = daoConfigMap.get(GiraffeHttpLogInfoDao.class).clone();
        wolfHttpLogInfoDaoConfig.initIdentityScope(type);

        wolfExceptionInfoDao = new GiraffeExceptionInfoDao(wolfExceptionInfoDaoConfig, this);
        wolfHttpLogInfoDao = new GiraffeHttpLogInfoDao(wolfHttpLogInfoDaoConfig, this);

        registerDao(GiraffeExceptionInfo.class, wolfExceptionInfoDao);
        registerDao(GiraffeHttpLogInfo.class, wolfHttpLogInfoDao);
    }
    
    public void clear() {
        wolfExceptionInfoDaoConfig.clearIdentityScope();
        wolfHttpLogInfoDaoConfig.clearIdentityScope();
    }

    public GiraffeExceptionInfoDao getGiraffeExceptionInfoDao() {
        return wolfExceptionInfoDao;
    }

    public GiraffeHttpLogInfoDao getGiraffeHttpLogInfoDao() {
        return wolfHttpLogInfoDao;
    }

}
